# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Go

permissions:
  contents: write

on:
  schedule:
    - cron: '0/10 * * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: node go.mjs
    - run: npm run build --if-present
    - run: npm test
    - uses: EndBug/add-and-commit@v9
      with:
        message: Add new instance
        committer_name: GitHub Actions
        committer_email: actions@github.com
